variables:
    mDOCKER_IMAGE: "windows-container/westerncore"
    mREPO_URL_SNAPSHOT: "${REPO_DOCKER_HOST}/${REPO_DOCKER_REGISTRY_SNAPSHOT}/windows-container/westerncore"
    mREPO_URL_RELEASE: "${REPO_DOCKER_HOST}/${REPO_DOCKER_REGISTRY_RELEASE}/windows-container/westerncore"
    mDOCKER_IMAGE_TEST: "windows-container/westerncoretest"
    mREPO_URL_SNAPSHOT_TEST: "${REPO_DOCKER_HOST}/${REPO_DOCKER_REGISTRY_SNAPSHOT}/windows-container/westerncoretest"
    mREPO_URL_RELEASE_TEST: "${REPO_DOCKER_HOST}/${REPO_DOCKER_REGISTRY_RELEASE}/windows-container/westerncoretest"
    WINDOWS_VERSION: "1909"
  
stages:
  - test
  - build

default:  
#  before_script:
#   - echo $REPO_DOCKER_PASSWORD | docker login -u $REPO_DOCKER_USER --password-stdin $REPO_DOCKER_HOST

build_job:
  stage: build
  tags: 
    - CICD-WIN03-1909
  script:
    - docker build -t ${mDOCKER_IMAGE}-${WINDOWS_VERSION} -f Western\Dockerfile .
    - docker tag ${mDOCKER_IMAGE}-${WINDOWS_VERSION} ${mREPO_URL_SNAPSHOT}-${WINDOWS_VERSION}:${CI_JOB_ID}
    - docker push ${mREPO_URL_SNAPSHOT}-${WINDOWS_VERSION}:${CI_JOB_ID}
 
test_job:
  stage: test
  tags: 
    - CICD-WIN03-1909
  script:
    - docker build -t ${mDOCKER_IMAGE_TEST}-${WINDOWS_VERSION} -f Western\Dockerfile .
    - docker tag ${mDOCKER_IMAGE_TEST}-${WINDOWS_VERSION} ${mREPO_URL_SNAPSHOT_TEST}-${WINDOWS_VERSION}:${CI_JOB_ID}
    - docker push ${mREPO_URL_SNAPSHOT_TEST}-${WINDOWS_VERSION}:${CI_JOB_ID}
