variables:
    mDOCKER_IMAGE: "windows-container/westerncore"
    mREPO_URL_SNAPSHOT: "${REPO_DOCKER_HOST}/${REPO_DOCKER_REGISTRY_SNAPSHOT}/windows-container/westerncore"
    mREPO_URL_RELEASE: "${REPO_DOCKER_HOST}/${REPO_DOCKER_REGISTRY_RELEASE}/windows-container/westerncore"
    WINDOWS_VERSION: "1909"
  
stages:
  - test
  - build
  
build_job:
  stage: build
# before_script:
#   - echo $REPO_DOCKER_PASSWORD | docker login -u $REPO_DOCKER_USER --password-stdin $REPO_DOCKER_HOST
  tags: 
    - CICD-WIN03-1909
  script:
    - docker build -t ${mDOCKER_IMAGE}-${WINDOWS_VERSION} -f Western\Dockerfile .
    - docker tag ${mDOCKER_IMAGE}-${WINDOWS_VERSION} ${mREPO_URL_SNAPSHOT}-${WINDOWS_VERSION}:${CI_JOB_ID}
    - docker push ${mREPO_URL_SNAPSHOT}-${WINDOWS_VERSION}:${CI_JOB_ID}
  

test_job:
  stage: test
  tags: 
    - CICD-WIN03-1909
  variables:
    test_path: "$project/Western.Test"
  before_script:
    - dotnet tool install dotnet-reportgenerator-globaltool --tool-path /tools
  script:
    - echo "western testing"
    - "cd $test_path"
    - dotnet test --logger "trx;LogFileName=western_test_results.xml" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=/out/testresults/coverage/ /p:Exclude="[xunit.*]*" --results-directory /out/testresults
